### ISSUE TITLE
Error when running on MacOS 

### ISSUE THREAD

**Issue by nvnunes** [DeepMLNet/PLplotNet#1]
Hello,

I'm trying to use PLplotNet on the Mac using Visual Studio for Mac. I've installed PLPlot on my system and downloaded PLplotNet via NuGet.

When I run the app, I get the following exception:

DllNotFoundException
API-MS-WIN-CRT-ENVIRONMENT-L1-1-0.DLL
  at (wrapper managed-to-native) PLplot.Native:_putenv_s (string,string)
  at PLplot.Native..cctor () [0x00049] in <839be5c188a24e59a7156a92b7df2f7b>:0

I've tried running the same project in Windows and it works just fine. So obviously this is something specific to running in Mono.

Would you have any thoughts on how I might work around this?

**Comment by nvnunes** [comment]
Hello,

After some more poking around, I figured out that instead of API-MS-WIN-CRT-ENVIRONMENT-L1-1-0.DLL you can use msvcrt.dll which works cross-platform. However, in OSX (not sure about other UNIX operating systems), the method for setting an environmental variable is different. Instead of "_putenv_s(s, s)" it's "putenv(s)" where "s" in the form "name=value".

To further complicate things, "RuntimeInformation.IsOSPlatform(OSPlatform.OSX)" doesn't seem to work correctly when running in Mono. I found an alternative check that does work:

`
Environment.OSVersion.Platform == PlatformID.Unix && File.Exists ("/usr/lib/libc.dylib")
`

Putting this all together, I came up with the following change to NativeHelper.cs which now works on both Windows and the Mac running in Mono:

        static Native()
        {
            // directory of executing program binary
            string exeDir = Path.GetDirectoryName(Assembly.GetEntryAssembly().Location);

            // On .Net core this assembly is not necessarily in the same directory as the
            // application main executable, where the native plplot.dll has been copied 
            // to (see build/PLplot.targets). We need to set PATH accordingly so that
            // the loader will find the unmanaged DLL.
            string oldPath = Environment.GetEnvironmentVariable("PATH");
            string newPath = exeDir + ";" + oldPath;
            Environment.SetEnvironmentVariable("PATH", newPath);

            // The NuGet package ships with the PLplot DLLs and supporting font and
            // color map files. These files get installed into the directory "plplot"
            // relative to the application main executable (see build/PLplot.targets).
            // For PLplot to find its support files, the environment variable 
            // PLPLOT_LIB must be set accordingly.                
            //
            // We have to call the CRT function _putenv to update the global _environ 
            // variable of the C runtime, since it is only populated at the start of
            // the program and not updated from the Windows environment block.
            string supPath = Path.Combine(exeDir, SupportDir);

            // RuntimeInformation.IsOSPlatform(OSPlatform.OSX) doesn't work correctly
            // in Mono. Instead check for OSX by looking for libc.dylib which requires
            // a different method to set the environment. 
            if (Environment.OSVersion.Platform == PlatformID.Unix && File.Exists ("/usr/lib/libc.dylib"))
            {
                putenv(string.Format("PLPLOT_LIB={0}", supPath));
            }
            else if (RuntimeInformation.IsOSPlatform(OSPlatform.Windows))
            {
                _putenv_s("PLPLOT_LIB", supPath);
            }

            //Console.WriteLine("Set PATH={0}", newPath);                
            //Console.WriteLine("Set PLPLOT_LIB={0}", supPath);                
        }

        [DllImport("API-MS-WIN-CRT-ENVIRONMENT-L1-1-0.DLL", EntryPoint = "_putenv_s", CallingConvention = CallingConvention.Cdecl)]
        private static extern int _putenv_s([MarshalAs(UnmanagedType.LPStr)] string name,
                                            [MarshalAs(UnmanagedType.LPStr)] string value);
   
        [DllImport("msvcrt.dll", EntryPoint = "putenv", CallingConvention = CallingConvention.Cdecl)]
        public static extern int putenv( string e );


Perhaps this is a change you might consider.

Best,
Nelson

**Comment by surban** [comment]
Hi Nelson,

sorry for replying so late, but somehow I missed the notification about the issue.

Actually setting the environment variables should only be necessary on Windows, because this is the only platform for which the native plplot.dll is included in the NuGet package. For Linux and MacOS I expect the library to be installed on the users system, i.e. in the system's dynamic library path. In that case setting PLPLOT_LIB should not be necessary, because the PLplot native library uses the compiled-in path for its supporting files (for example /usr/share/plplot5.10.0 on Linux).

Also I don't understand how the original error you reported happens, since _putenv_s should only be called if RuntimeInformation.IsOSPlatform(OSPlatform.Windows) evaluates to true. Is it possible, that Mono somehow returns true for this check on macOS although it shouldn't? 

Sebastian

**Comment by surban** [comment]
This seems to be a bug in Mono when referencing a .Net Standard library from a .NET Framework app. See mono/mono#7011. This issue does not occur when you reference the library from a .NET core 2.0 app.

**Comment by surban** [comment]
Since mono/mono#6926 has been merged, I am assuming that this issue is fixed.
